name = "weak_collatz_tm"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["WeakCollatzTm"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "WeakCollatzTm"

[[lean_exe]]
name = "Sim45"
srcDir = "WeakCollatzTm/Tm45_3"

[[lean_exe]]
name = "Sim61"
srcDir = "WeakCollatzTm/Tm61_2"

[[lean_exe]]
name = "Coverage61"
srcDir = "WeakCollatzTm/Tm61_2"

[[lean_exe]]
name = "Sim56"
srcDir = "WeakCollatzTm/Tm56_2"

[[lean_exe]]
name = "Coverage56"
srcDir = "WeakCollatzTm/Tm56_2"

